### ISSUE TITLE
QA

### ISSUE THREAD

**Issue by henryvulcan** [bitterteasweetorange/nvim#14]
My nvim shows 'x' is defined but never used 3 times

**Comment by bitterteasweetorange** [comment]
Could you please provide more information

**Comment by henryvulcan** [comment]
<img width="1800" alt="Screenshot 2023-11-06 at 02 37 48" src="https://github.com/bitterteasweetorange/nvim/assets/92013160/9b3e61fb-251c-4b8b-9400-a5d4d2132c95">

This is still the problem I have to find, is it possible to do lsp using additional Typescript.nvim or I try compliant configuration and Typescript-tools also have the same problem

**Comment by bitterteasweetorange** [comment]
Both ESLint and tsserver threw errors, which could be considered normal. In VSCode, I observed one error being displayed. I'm uncertain if VSCode do some kind of magic to prevent tsserver errors from appearing as diagnostics.


https://www.reddit.com/r/neovim/comments/11j0myp/lsp_how_to_disable_diagnostic_and_formatting_from/
https://stackoverflow.com/questions/71948571/both-eslint-and-typescript-report-duplicate-warnings-in-vscode

**Comment by bitterteasweetorange** [comment]
https://github.com/bitterteasweetorange/nvim/pull/15
