### ISSUE TITLE
how to import aliases with use typescript-tool.nvim?

### ISSUE THREAD

**Issue by unrealhenry** [bitterteasweetorange/nvim#19]
I read the docs of the repo but there is no importModuleSpecifierPreference, but when I placed an issue I was instructed to use importModuleSpecifierEnding. I remember these are two completely different options? Do you have a solution to the problem?
<img width="1908" alt="Screenshot 2023-12-04 at 23 37 21" src="https://github.com/bitterteasweetorange/nvim/assets/92013160/c643fbaf-3fd1-4613-a7c2-add6ae181515">

**Comment by bitterteasweetorange** [comment]
```
    tsserver_file_preferences = {
      importModuleSpecifierPreference = 'non-relative',
    },
```

They look quite similar.
