### ISSUE TITLE
Problem when using visual block mode.

### ISSUE THREAD

**Issue by MoLiYue** [bitterteasweetorange/nvim#2]
in function <...ite/pack/packer/start/galaxyline.nvim/lua/galaxyline.lua:32> function: builtin#18 /Users/moliyue/.config/nvim/lua/p-status.lua:73: attempt to concatenate a nil value

**Comment by MoLiYue** [comment]
add `[''] = nord_colors.yellow,` in the .config/nvim/lua/p-status.lua:63 mode_color{}

**Comment by MoLiYue** [comment]
add ['^V'] = nord_colors.yellow, in the .config/nvim/lua/p-status.lua:63 mode_color{}

NOTICE！！！
^V is not '^V', it can be input by `Ctrl V + Ctrl V`.
It is ascii 0x16, and corresponding to the character 'CtrlV'

**Comment by bitterteasweetorange** [comment]
> add ['^V'] = nord_colors.yellow, in the .config/nvim/lua/p-status.lua:63 mode_color{}
> 
> NOTICE！！！ ^V is not '^V', it can be input by `Ctrl V + Ctrl V`. It is ascii 0x16, and corresponding to the character 'CtrlV'

Thank you for the detailed issue report.
